version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

jobs:
  build:
    working_directory: ~/play_be
    docker:
      - image: circleci/node:10.12.0-stretch
        environment:
          PGHOST: 127.0.0.1
          PGUSER: play_app_test
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: play_app_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: play_app_test

    steps:
      - checkout

      - run: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: install postgresql-client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: npm test